version: '3.1'

services:
  ewm-service:
    build: ./ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-server-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=ewm-server-db
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - EWM-STATS.URL=http://stats-server:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ewm-server-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  stats-server:
    build: ./ewm-stats
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_NAME=ewm-stats-db
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ewm-stats-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root