CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       TEXT                                    NOT NULL,
    uri       TEXT                                    NOT NULL,
    ip        TEXT                                    NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);